### ISSUE TITLE
Removes bugs from FAQ-Section and make it responsive.

### ISSUE THREAD

**Issue by shashank-iter** [Web3-Bharat-ITER/UI-Component-Library#10]
**Anyone who is interested in solving this issue can comment below, we will assign this issue to him/her. 
The main task is to properly add accordion and add responsiveness to the FAQ-Section.**

**Comment by Vinitpal** [comment]
Please assign this to me

**Comment by shashank-iter** [comment]
@Vinitpal Make sure you add some proper code and after the completion kindly add a screenshot of the UI. Is it okay for you ?

**Comment by Vinitpal** [comment]
Yes, it's okay, I can do that.

**Comment by shashank-iter** [comment]
@Vinitpal Assigned it to you.
