### ISSUE TITLE
Add a simple responsive Navbar component

### ISSUE THREAD

**Issue by shashank-iter** [Web3-Bharat-ITER/UI-Component-Library#12]
### The key task is to add a simple responsive Navbar component. It should have at least 4 tabs with a dropdown menu. You can make it more creative according to you.

**Comment by borkarSahil** [comment]
Hey I am interested  in making a navbar .
 Can you assign me ? and Is using bootstrap valid ?

**Comment by shashank-iter** [comment]
@borkarSahil  Yeah you can make it using bootstrap but just try to a little bit of creativity to it. I am assigning it you . Kindly add a screenshot of you work while making the PR. Is it okay ??

**Comment by coder-chahal** [comment]
Hlo sir, plzz kindly assign this issue to me
this is my first hactoberfest, i'm very intrested to contributing.

**Comment by shashank-iter** [comment]
@coder-chahal  and @borkarSahil  you both can work on this issue and raise a valid PR, kindly read contribution guidelines and add screenshots of your work with PR. Happy Hacktober Fest.

**Comment by shivamp1998** [comment]
Can I work on it too?

**Comment by shashank-iter** [comment]
> Can I work on it too? 

Yes you can and try to add some creativity to it. Kindly add the screenshot of the work while making the PR. Do code it properly.
