### ISSUE TITLE
I want to add login and signup page

### ISSUE THREAD

**Issue by kishanlalchoudhary** [Web3-Bharat-ITER/UI-Component-Library#137]

**Comment by kishanlalchoudhary** [comment]
![Screenshot (50)](https://user-images.githubusercontent.com/107745828/197403430-d8d8527e-cc55-4f78-9ce6-813bd94a5630.png)
![Screenshot (51)](https://user-images.githubusercontent.com/107745828/197403433-66c3acfc-ac3d-4194-98f8-ab748822c83d.png)

**Comment by kishanlalchoudhary** [comment]
can i add this under hactoberfest2022

**Comment by shashank-iter** [comment]
@kishanlalchoudhary Yes you can make a PR regarding that and kindly add these screenshots there too. We will merge it.

**Comment by shashank-iter** [comment]
@kishanlalchoudhary Yes you can make a PR regarding that and kindly add these screenshots there too. We will merge it.

**Comment by kishanlalchoudhary** [comment]
I have many components like this about us page and contact us that too responsive navigation bar with animation and responsive

**Comment by kishanlalchoudhary** [comment]
I will make separate pr of each if ppssible

**Comment by shashank-iter** [comment]
yeah sure @kishanlalchoudhary you can make one PR per component but add screenshots with every PR

**Comment by shashank-iter** [comment]
yeah sure @kishanlalchoudhary you can make one PR per component but add screenshots with every PR

**Comment by kishanlalchoudhary** [comment]
Ok np
