### ISSUE TITLE
Login Page

### ISSUE THREAD

**Issue by AliReza1083** [Web3-Bharat-ITER/UI-Component-Library#24]
I want to add a new UI component for Login Page.
Please assign it to me.

**Comment by AliReza1083** [comment]
I'm done with the Issue, Can I make PR?

**Comment by AliReza1083** [comment]
but before doing that, Please assign it to me..
Thanks

**Comment by shashank-iter** [comment]
@AliReza1083 Surely you can add the login page but try to be creative while doing that and code it properly. Kindly add a screenshot of your work while making a PR.
