### ISSUE TITLE
Login cum Sign up page 

### ISSUE THREAD

**Issue by Princerey** [Web3-Bharat-ITER/UI-Component-Library#29]
Hey @shashank-iter Can I also work on login cum sign up page UI  ? Could you please assign me this ?

**Comment by shashank-iter** [comment]
@Princerey Yeah sure, assigning it to you. Don't forget to add a screenshot of your work while making a PR.

**Comment by Princerey** [comment]
Thanks @shashank-iter .
Please check once I have created the PR.
